services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"      # REST
      - "6334:6334"      # gRPC (optional)
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: rag-app
    depends_on:
      - qdrant
    environment:
      # these get defaulted by .env (see .env.example below)
      QDRANT_URL: ${QDRANT_URL:-http://qdrant:6333}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION:-rag_rh_chunks}
      # LLM settings (optional; for local you can leave unset)
      LLM_BASE_URL: ${LLM_BASE_URL:-}
      LLM_MODEL: ${LLM_MODEL:-}
      LLM_API_KEY: ${LLM_API_KEY:-}
    ports:
      - "8501:8501"      # Streamlit UI
    # Streamlit starts in the Dockerfile CMD; nothing else to run here
    healthcheck:
      # If your app image has curl or wget (our Dockerfile installs wget),
      # this checks Streamlit's health endpoint.
      test: ["CMD-SHELL", "wget -qO- http://localhost:8501/_stcore/health >/dev/null || curl -fsS http://localhost:8501/_stcore/health >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    volumes:
      - ./app/rag_app:/app/rag_app

volumes:
  qdrant_storage: